# Generated by Django 2.2.2 on 2019-10-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0003_trainer_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='file',
            field=models.FileField(default='', upload_to='pdf'),
            preserve_default=False,
        ),
    ]
