# Generated by Django 2.2.2 on 2019-10-12 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0004_meals_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mealId',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='type',
        ),
        migrations.AddField(
            model_name='profile',
            name='mealId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='fit.Meals'),
            preserve_default=False,
        ),
    ]
