# Generated by Django 2.2.2 on 2019-10-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0005_auto_20191012_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='mealId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='fit.Meals'),
            preserve_default=False,
        ),
    ]
